DEF CGB_A_INIT EQU $11 ; Accumulator starting value on a Gameboy Color

; Sound control
DEF CHANNEL_CONTROL EQU $FF24
DEF CHANNEL_OUTPUT_CONTROL EQU $FF25
DEF DISABLE_CHANNELS_REGISTERS EQU $FF26

; Sound Channel 1
DEF CHANNEL1_SWEEP EQU $FF10
DEF CHANNEL1_LENGTH EQU $FF11
DEF CHANNEL1_VOLUME EQU $FF12
DEF CHANNEL1_LOW_FREQ EQU $FF13
DEF CHANNEL1_HIGH_FREQ EQU $FF14

; Sound Channel 2
DEF CHANNEL2_LENGTH EQU $FF16
DEF CHANNEL2_VOLUME EQU $FF17
DEF CHANNEL2_LOW_FREQ EQU $FF18
DEF CHANNEL2_HIGH_FREQ EQU $FF19

; Sound channel 3
DEF CHANNEL3_ON_OFF EQU $FF1A
DEF CHANNEL3_LENGTH EQU $FF1B
DEF CHANNEL3_OUTPUT EQU $FF1C
DEF CHANNEL3_LOW_FREQ EQU $FF1D
DEF CHANNEL3_HIGH_FREQ EQU $FF1E
DEF WPRAM EQU $FF30

; Sound channel 4
DEF CHANNEL4_LENGTH EQU $FF20
DEF CHANNEL4_VOLUME EQU $FF21
DEF CHANNEL4_POLY EQU $FF22
DEF CHANNEL4_RESTART EQU $FF23

; LCD
DEF LCD_CONTROL EQU $FF40
DEF STAT_CONTROL EQU $FF41
DEF LCD_BASE_CONTROL EQU %11110011
DEF SCROLL_X EQU $FF43
DEF SCROLL_Y EQU $FF42
DEF LY EQU $FF44
DEF LYC EQU $FF45
DEF WX EQU $FF4B
DEF WY EQU $FF4A

; Cartridge Registers
DEF ROM_BANK_SWITCH EQU $2000

; VRAM
DEF VRAM_START EQU $8000
DEF VRAM_BG_START EQU $9800
DEF VRAM_BANK_SELECT EQU $FF4F

; Characters
DEF TM_CHARACTER EQU $88

; Joypad
DEF JOYPAD_REGISTER EQU $FF00

; Interrupts
DEF INTERRUPT_REQUEST EQU $FF0F
DEF INTERRUPT_ENABLED EQU $FFFF
DEF NO_INTERRUPT EQU 0
DEF VBLANK_INTERRUPT EQU (1 << 0)
DEF LCD_STAT_INTERRUPT EQU (1 << 1)
DEF TIMER_INTERRUPT EQU (1 << 2)
DEF SERIAL_INTERRUPT EQU (1 << 3)
DEF JOYPAD_INTERRUPT EQU (1 << 4)

; Misc registers
DEF DIV_REGISTER EQU $FF04
DEF PALETTE_REGISTER EQU $FF47
DEF KEY1 EQU $FF4D

; Game registers
DEF FRAME_COUNTER EQU $C000
DEF HARDWARE_TYPE EQU $C001
DEF RANDOM_REGISTER EQU $C002
DEF PLAYER_STRUCT EQU $C003

DEF CURRENTLY_LOADED_MAP EQU $C018
DEF OLD_SCROLL_X EQU $C019
DEF OLD_SCROLL_Y EQU $C01A

DEF BOTTOM_LEFT_VRAM_START_L EQU $C01B
DEF BOTTOM_LEFT_VRAM_START_H EQU $C01C
DEF BOTTOM_LEFT_MAP_START_L EQU $C01D
DEF BOTTOM_LEFT_MAP_START_H EQU $C01E

DEF TOP_RIGHT_VRAM_START_L EQU $C01F
DEF TOP_RIGHT_VRAM_START_H EQU $C020
DEF TOP_RIGHT_MAP_START_L EQU $C021
DEF TOP_RIGHT_MAP_START_H EQU $C022

DEF LEFT_LEFT_VRAM_START_L EQU $C023
DEF LEFT_LEFT_VRAM_START_H EQU $C024
DEF LEFT_LEFT_MAP_START_L EQU $C025
DEF LEFT_LEFT_MAP_START_H EQU $C026

DEF TOP_LEFT_VRAM_START_L EQU $C027
DEF TOP_LEFT_VRAM_START_H EQU $C028
DEF TOP_LEFT_MAP_START_L EQU $C029
DEF TOP_LEFT_MAP_START_H EQU $C02A

DEF GRAVITY_TIMER EQU $C02B
DEF GRAVITY_LIMITER EQU $C02C
DEF MAP_PTR_H EQU $C02D
DEF MAP_PTR_L EQU $C02E
DEF KEYS_DISABLED EQU $C02F
DEF MUSIC_CHANNEL_1 EQU $C030
DEF MUSIC_CHANNEL_2 EQU $C035
DEF MUSIC_CHANNEL_WAVE EQU $C03A
DEF MUSIC_CHANNEL_NOISE EQU $C03F
DEF ANIMATION_TIMER EQU $C045
DEF TIMER_REGISTER EQU $C046 ; Take 3 bytes
DEF TIMER_FRAME_COUNTER_REGISTER EQU $C049
DEF OAM_SRC_START EQU $C100
DEF MAP EQU $C1A0


; Other registers
DEF INTRO_COUNTER EQU $C028
DEF CREDITS_CURRENT_LINE EQU $C029
DEF CREDITS_LAST_ADDR_H EQU $C02A
DEF CREDITS_LAST_ADDR_L EQU $C02B
DEF CREDITS_LINE_POS EQU $C02C
DEF CREDITS_SLIDING EQU $C02D
DEF CREDITS_LINES EQU $C02E

; Map
DEF MAP_SIZE_X_OFF     EQU $0
DEF MAP_SIZE_Y_OFF     EQU $1
DEF MAP_NB_TARGETS_OFF EQU $2
DEF MAP_TAGS_OFF       EQU $3
DEF MAP_PAL_OFF        EQU $7
DEF MAP_TILES_OFF      EQU $47
DEF TILE_PALETTE       EQU %11100000
DEF TILE_IS_SOLID      EQU %00010000
DEF TILE_TEXTURE       EQU %00011111

; Game constants
DEF DMG_BG_PALETTE EQU %11011000
DEF DMG_OBP0_PALETTE EQU %11011000
DEF DMG_OBP1_PALETTE EQU %11011000
DEF PLAYER_SPRITE_NBR EQU $80
DEF PLAYER_SPRITE_WALK_NBR EQU $90
DEF PLAYER_SPRITE_JUMP_NBR EQU $A0
DEF PLAYER_SPRITE_PAINT_NBR EQU $A4
DEF GRAVITY_CONSTANT EQU $6
DEF PLAYER_POSITION_X EQU $40
DEF PLAYER_POSITION_Y EQU $40
DEF ANIMATION_TIME EQU $7
DEF PAINTING_TIME EQU $A

; Music structure
DEF MUSIC_TIMER_OFF EQU $0
DEF MUSIC_PTR_H_OFF EQU $1
DEF MUSIC_PTR_L_OFF EQU $2
DEF MUSIC_START_PTR_H_OFF EQU $3
DEF MUSIC_START_PTR_L_OFF EQU $4

; Basic object structure
DEF BASIC_OBJECT_STRUCT_X_OFF EQU $0
DEF BASIC_OBJECT_STRUCT_X_SIZE_OFF EQU $1
DEF BASIC_OBJECT_STRUCT_X_SPEED_OFF EQU $2
DEF BASIC_OBJECT_STRUCT_Y_OFF EQU $3
DEF BASIC_OBJECT_STRUCT_Y_SIZE_OFF EQU $4
DEF BASIC_OBJECT_STRUCT_Y_SPEED_OFF EQU $5

; Displayable object structure
DEF DISPLAYABLE_OBJECT_STRUCT_BASIC_OBJECT EQU $0
DEF DISPLAYABLE_OBJECT_STRUCT_SPRITE EQU $6
DEF DISPLAYABLE_OBJECT_STRUCT_ORIENTATION EQU $7

; End of player struct
DEF HAS_DOUBLE_JUMP_OFF EQU $8

DEF MAP_VRAM_START_BOTTOM_LEFT EQU $9A81
DEF MAP_VRAM_START_TOP_RIGHT EQU $9836
DEF MAP_VRAM_START_LEFT_LEFT EQU $9820
DEF MAP_VRAM_START_TOP_LEFT EQU $9801
DEF MAP_MAP_START_LEFT_LEFT EQU (MAP - 1 + MAP_TILES_OFF)

; DMG Palette
DEF BGP EQU $FF47
DEF OBP0 EQU $FF48
DEF OBP1 EQU $FF49

; GBC Palette
DEF BGPI EQU $FF68
DEF BGPD EQU $FF69
DEF OBPI EQU $FF6A
DEF OBPD EQU $FF6B

; SGB Commands
DEF PAL_TRN EQU $59
DEF DATA_SND EQU $79
DEF MLT_REQ EQU $89
DEF CHR_TRN EQU $99
DEF PCT_TRN EQU $A1
DEF MASK_EN EQU $B9

; DMA
DEF START_DMA EQU $FF46
DEF DMA_DELAY EQU $28
DEF DMA EQU $FF80

; Sprite offsets
DEF SPRITE_POSITION_Y EQU $0
DEF SPRITE_POSITION_X EQU $1
DEF SPRITE_TILE_NBR EQU $2
DEF SPRITE_ATTRIBUTE_FLAGS EQU $3

DEF QUAVER EQU $E
DEF INTROLN EQU $5

DEF MQUAVER EQU $C
